title: absurd.world
email: tim@elbart.com
description: >- # this means to ignore newlines until "baseurl:"
  The absurd world we live in - reflecting thoughts ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://absurd.world" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: elbartus
github_username:  elbart

# Build settings
theme: minima
plugins:
  - jekyll-feed
