name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Install jekyll
      run: gem install bundler jekyll
    - name: Install dependencies
      run: bundle install
    - name: Build the site
      run: bundle exec jekyll build
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE }}
    - name: rsync to absurd.world
      run: rsync -avz ./_site/* root@absurd.world:/usr/share/nginx/html/absurdworld
      
